### ISSUE TITLE
PLAYTIME IN SCOREBOARD IS NOT WORKING

### ISSUE THREAD

**Issue by HonzasikCZ** [GRX005/PlaytimeLink#7]
Using https://github.com/NEZNAMY/TAB
![Image](https://github.com/user-attachments/assets/a937ab91-cd83-4865-af7c-021247a509b9)

**Comment by HonzasikCZ** [comment]
Hello! 

Sorry for the inaccurate information but I was getting pretty tired.
The placeholder doesn't work in TAB or anywhere else.

**Comment by GRX005** [comment]
Hi, no idea what's the issue there, no one else reported such, and I couldn't replicate your problem with any settings. Was it working before?

**Comment by HonzasikCZ** [comment]
For a while I noticed that it was working on the lobby but it's not working there now..I just put the plugins on the server and tried it...Now it's not working on the lobby but it's working on the other server where it wasn't working before :sob:

**Comment by pintoso** [comment]
I have the same problem, I use placeholders to make a top 10 with DiscordSRV.
It worked for a while btw.

**Comment by pintoso** [comment]
Velocity 3.4.0-SNAPSHOT (git-1db8c8c6-b458)
Purpur 1.21.3-2358-16ce24a (MC: 1.21.3)

Playtime velocity config:
```yaml
#Velocity playtime logger.
file-version: 11
isDataFileUpToDate: true
Messages:
  NO_CONSOLE_USE: The console doesn't have a playtime.
  PLAYTIME_YOURS: '§8----------------------\n§aYour playtime: %weeks% weeks %days% days %hours% hours %minutes% minutes %seconds% secs. Place: %place%\n§8----------------------'
  NO_PLAYER: §cNo player found with this name.
  PLAYTIME_OTHERS: '§8----------------------\n§a%player%''s playtime: %weeks% weeks %days% days %hours% hours %minutes% minutes %seconds% secs. Place: %place%\n§8----------------------'
  NO_PERMISSION: §cYou don't have permission for this command.
  CONFIG_RELOAD: §aThe config has been reloaded.
  PTRESET: §a%player%'s playtime has been reset.
  PTRESET_HELP: §a/playtimereset [player]
  PTRESETALL: §aAll playtimes have been reset.
  PTRESETALL_CONFIRM: §aIf you are sure to delete every playtime, type /ptresetall confirm
  PTSET: §aSet %player%'s playtime to %ms% ms.
  INVALID_ARGS: §cYou've entered invalid arguments.
  TOP_PLAYTIME_HEADER: '§aPlaytime toplist: '
  TOP_PLAYTIME_VALUES: '§3%place%.: §a%player%: %weeks% weeks %days% days %hours% hours %minutes% minutes %seconds% secs.'
  TOP_PLAYTIME_FOOTER: §a-------------------------------------
  NO_SPAM: §cDo not spam the command. You have to wait %seconds% secs to do that again.
  INVALID_VALUE: §cYou've entered an invalid value.

Data:
  TOPLIST_LIMIT: 100
  BSTATS: false
  #If you are using placeholders with the PlaytimeLink plugin, and have issues with them, try enabling this.
  PRELOAD_PLACEHOLDERS: true
  #Ex: 1000 for 1 second.
  SPAM_LIMIT: 1
  #Choices are: "VANILLA" or "MINIMESSAGE". Use minimessage if you want gradients.
  CONFIG_SERIALIZER: VANILLA
  #Choices are: "YMLFILE" or "DATABASE".
  DATA_METHOD: YMLFILE
  DATABASE: #Only applies if you chose DATABASE as DATA_METHOD, leave password at null if the db doesn't have one, ex: jdbc:mariadb://127.0.0.1:3306/playtime?user=root&password=
    ADDRESS: 127.0.0.1
    PORT: 3306
    DB_NAME: playtime
    USERNAME: root
    PASSWORD: null
  CHECK_FOR_UPDATES: true
  CACHING: #Should improve performance when turned on. If there are issues with the plugin, try turning it off. The 2nd option is about how often unneeded entries are cleared from the cache, in ms. Note: Toplist limit can't be reloaded if this is turned on.
    USE_CACHE: false
    CACHE_UPDATE_INTERVAL: 6000
  PERMISSIONS: #Permissions are not used by default, they can be turned on if needed.
    VIEW_OWN_TIME: false
    VIEW_OTHERS_TIME: false
    VIEW_TOPLIST: false
  #The "vpt.rewards.exempt" perm can't be checked for offline players, so they don't get rewards by default when their pt is increased.
  OFFLINES_SHOULD_GET_REWARDS: false

#You can define your rewards under 'Rewards:' with the following format: [space]'playtime in milliseconds': command
#(1sec = 1000ms, you need to have one space at the start of very line)
# '15000': lpv user %player% parent set group #Example command.
Rewards: null
```

Playtime link config:
```yaml
#Velocity playtime logger placeholderAPI extension.
file-version: 3
Messages:
  LOADING: "..."
  NOT_IN_TOPLIST: "Not in toplist"
Data:
  CHECK_FOR_UPDATES: true
  BSTATS: false
#Same as in the main plugin. ([space]'time in millisecs': cmd) (ex: '10000': say hello)
Rewards:
```
